name: wareco_2
description: WARECO

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.4
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  http: ^0.13.5
  connectivity_plus: ^3.0.2
  flutter_svg: ^1.1.6

  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.2.1
  build_runner: ^2.3.2
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  riverpod_generator: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/



flutter_icons:
  android: 'launcher_icon'
  image_path: 'assets/png/sm_logo.png'
  min_sdk_android: 21

